### ISSUE TITLE
Put notification text on page as notification not as visible on all platforms

### ISSUE THREAD

**Issue by earseneau** [google/paseos#9]
On Mac, the notification is showing up as a little slider on top right of screen for just a little bit.

Thought it might be useful to include the text of the notification on the page that raised the notification.  So then its visible at all times.

**Comment by diegowilson** [comment]
The text in the notification should also appear in a card in the journey window (the one with next and back buttons). Isn't that what you're seeing? If not then it's a bug.

**Comment by earseneau** [comment]
Ok, my bad, my brain didnt match the strings, closing.
